# Generated by Django 4.2.23 on 2025-07-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sasana',
            fields=[
                ('id_sasana', models.AutoField(primary_key=True, serialize=False)),
                ('nama_sasana', models.CharField(max_length=255)),
                ('sejak', models.IntegerField()),
                ('alamat_sasana', models.TextField()),
                ('kelurahan', models.CharField(max_length=100)),
                ('kecamatan', models.CharField(max_length=100)),
                ('kota_kabupaten', models.CharField(max_length=100)),
                ('provinsi', models.CharField(max_length=100)),
                ('lattitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('jumlah_instruktur', models.IntegerField()),
                ('jumlah_peserta', models.IntegerField()),
                ('peserta_aktif', models.IntegerField()),
                ('jumlah_latihan_per_minggu', models.IntegerField()),
                ('link_gmap', models.URLField()),
                ('profile', models.ImageField(upload_to='profile_sasana/')),
            ],
        ),
    ]
