# Generated by Django 4.2.20 on 2025-07-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sasana', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sasana',
            name='lattitude',
        ),
        migrations.RemoveField(
            model_name='sasana',
            name='longitude',
        ),
    ]
